# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.3"
ports: "80:80;4000:4000;4100:4100;127.0.0.1:2222:22"
secrets: mistral_api_key

config_file:
  template: "copilot-server/src/config.ts.dist"
  target: "copilot-server/src/config.ts"


command:
  build: |
      if [ ! -f node_modules ]; then
          npm update
      fi

  run:


  vite:
      - npm run dev

  dev:
      - "D: npm run dev"


  update:
    - "npm update"


  killall:
    - killall jekyll
